### ISSUE TITLE
AttributeError: 'ZeroPadding2D' object has no attribute 'name'

### ISSUE THREAD

**Issue by raphaeli** [tdeboissiere/VGG16CAM-keras#1]
Hi,
I have a problem with VGGCAM16. In your model definition there is no name passed (e.g. convolution2d_13).
Do the weights in h5 include layers' names definition? Do I need to update with latest keras version?
The error is:
if model.layers[k].name == "convolution2d_13":
    AttributeError: 'ZeroPadding2D' object has no attribute 'name'

thank you

**Comment by tdeboissiere** [comment]
Hi,

what is your keras version ? 
With keras 1.0.4, when I call:

`
model = VGGCAM(3)
Then I can do:
for l in model.layers:
    print l.name

output: 
zeropadding2d_1
convolution2d_1
...
`
So I don't need to define a name. You could try to set each layer name manually with layer.name = "...". 

If it does not work, time to upgrade your keras version.

**Comment by raphaeli** [comment]
Yes, it was time. Upgraded to 1.0.7 and works fine.
Thank you
