### ISSUE TITLE
Some problems about model.layers[-1].W.T

### ISSUE THREAD

**Issue by JagnDC** [tdeboissiere/VGG16CAM-keras#4]
Could you tell me 
`WT = model.layers[-1].W.T`
How can I use it？

**Comment by JagnDC** [comment]
Now, I solve this problem.
`WT = model.layers[-1].weights[0].transpose()`

**Comment by Junst** [comment]
I LOVE U. Really. I use my time for 5 hours to resolve this problem. Thx. Very Much
